/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "surface-container": "#201f1f",
        "background": "#131313",
        "tertiary-container": "#e5e2e1",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#3e4c00",
        "secondary": "#c8c6c5",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#1b1b1b",
        "primary-container": "#caf300",
        "secondary-container": "#474746",
        "inverse-primary": "#536600",
        "on-surface-variant": "#c5c9ac",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-container": "#596c00",
        "on-secondary": "#303030",
        "secondary-fixed": "#e4e2e1",
        "error": "#ffb4ab",
        "on-tertiary-container": "#656464",
        "primary": "#ffffff",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#313030",
        "on-secondary-container": "#b6b5b4",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#313030",
        "on-primary-fixed": "#171e00",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#2a3400",
        "on-tertiary-fixed-variant": "#474746",
        "outline-variant": "#444932",
        "tertiary-fixed": "#e5e2e1",
        "surface-bright": "#393939",
        "surface-tint": "#b0d500",
        "tertiary": "#ffffff",
        "on-error": "#690005",
        "primary-fixed": "#caf300",
        "outline": "#8f9378",
        "on-background": "#e5e2e1",
        "on-secondary-fixed-variant": "#474746",
        "surface-dim": "#131313",
        "primary-fixed-dim": "#b0d500",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1"
      },
      fontFamily: {
        "h2": ["Lexend-Bold"],
        "body-md": ["Inter-Regular"],
        "h3": ["Lexend-Bold"],
        "body-lg": ["Inter-Regular"],
        "h1": ["Lexend-ExtraBold"],
        "label-caps": ["Inter-Bold"]
      },
      spacing: {
        "sm": "12px",
        "base": "8px",
        "md": "24px",
        "margin": "20px",
        "lg": "40px",
        "xs": "4px",
        "xl": "64px",
        "gutter": "16px"
      }
    },
  },
  plugins: [],
}