/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        "outline": "#8f9378",
        "on-error": "#690005",
        "secondary-fixed": "#e4e2e1",
        "on-secondary": "#303030",
        "on-primary-container": "#596c00",
        "secondary": "#c8c6c5",
        "on-secondary-container": "#b6b5b4",
        "on-background": "#e5e2e1",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#caf300",
        "surface-container": "#201f1f",
        "primary-fixed-dim": "#b0d500",
        "on-tertiary-fixed": "#1b1b1b",
        "primary": "#ffffff",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary": "#ffffff",
        "surface-tint": "#b0d500",
        "tertiary-fixed": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#2a3400",
        "tertiary-container": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#171e00",
        "primary-container": "#caf300",
        "on-tertiary-container": "#656464",
        "inverse-primary": "#536600",
        "on-tertiary": "#313030",
        "surface-bright": "#393939",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "on-surface-variant": "#c5c9ac",
        "surface": "#131313",
        "secondary-container": "#474746",
        "on-secondary-fixed": "#1b1c1c",
        "error-container": "#93000a",
        "outline-variant": "#444932",
        "on-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#3e4c00",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "gutter": "16px",
        "md": "24px",
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "lg": "40px",
        "margin": "20px"
      },
      fontFamily: {
        "body-md": ["Inter_400Regular"],
        "label-caps": ["Inter_700Bold"],
        "h3": ["Lexend_700Bold"],
        "h1": ["Lexend_800ExtraBold"],
        "body-lg": ["Inter_400Regular"],
        "h2": ["Lexend_700Bold"],
        "lexend": ["Lexend_400Regular", "Lexend_700Bold", "Lexend_800ExtraBold"],
        "inter": ["Inter_400Regular", "Inter_500Medium", "Inter_700Bold"],
        "headline": ["PublicSans_700Bold"],
        "display": ["PublicSans_700Bold"],
        "body": ["PublicSans_400Regular"],
        "label": ["PublicSans_400Regular"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "h1": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
